import { mkdir, writeFile } from 'fs/promises'
import path from 'path'
import type { AppConfig } from '../schemas'

export interface ScaffoldWriteResult {
  outputDir: string
  files: string[]
}

function sanitizeName(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-') || 'appforge-export'
}

function buildHtml(config: AppConfig) {
  const pages = config.ui.pages
    .map((page) => `<li><strong>${page.name}</strong> <span>${page.route}</span></li>`)
    .join('')

  const endpoints = config.api.endpoints
    .map((endpoint) => `<li><strong>${endpoint.method}</strong> ${endpoint.route}</li>`)
    .join('')

  const tables = config.database.tables
    .map((table) => `<li><strong>${table.name}</strong> (${table.columns.length} columns)</li>`)
    .join('')

  const roles = config.auth.roles
    .map((role) => `<li><strong>${role.name}</strong>: ${role.permissions.join(', ')}</li>`)
    .join('')

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${config.meta.appName}</title>
    <style>
      :root { color-scheme: dark; }
      body { margin: 0; font-family: Inter, system-ui, sans-serif; background: #09090b; color: #f4f4f5; }
      .wrap { max-width: 1100px; margin: 0 auto; padding: 48px 24px 72px; }
      .hero { display: grid; gap: 12px; margin-bottom: 28px; }
      .badge { display: inline-flex; width: fit-content; padding: 6px 10px; border-radius: 999px; background: rgba(59,130,246,.18); color: #bfdbfe; font-size: 12px; letter-spacing: .08em; text-transform: uppercase; }
      h1 { font-size: clamp(40px, 6vw, 68px); line-height: .95; margin: 0; }
      p { color: #a1a1aa; line-height: 1.6; margin: 0; }
      .grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); margin-top: 24px; }
      .card { background: #111114; border: 1px solid #27272a; border-radius: 20px; padding: 20px; }
      .card h2 { margin: 0 0 12px; font-size: 16px; }
      ul { list-style: none; padding: 0; margin: 0; display: grid; gap: 10px; }
      li { color: #d4d4d8; font-size: 14px; }
      code { color: #93c5fd; }
      .meta { margin-top: 16px; font-size: 13px; color: #71717a; }
    </style>
  </head>
  <body>
    <div class="wrap">
      <div class="hero">
        <div class="badge">AppForge Exported App</div>
        <h1>${config.meta.appName}</h1>
        <p>${config.meta.description}</p>
        <p>Generated at <code>${config.meta.generatedAt}</code> with ${config.auth.provider} auth and ${config.database.tables.length} tables.</p>
      </div>

      <div class="grid">
        <section class="card">
          <h2>Pages</h2>
          <ul>${pages}</ul>
        </section>
        <section class="card">
          <h2>API</h2>
          <ul>${endpoints}</ul>
        </section>
        <section class="card">
          <h2>Database</h2>
          <ul>${tables}</ul>
        </section>
        <section class="card">
          <h2>Auth</h2>
          <ul>${roles}</ul>
        </section>
      </div>

      <div class="meta">Use <code>npm start</code> to run the exported app.</div>
    </div>
  </body>
</html>`
}

export function buildAppScaffold(config: AppConfig) {
  const appName = sanitizeName(config.meta.appName)

  const packageJson = {
    name: appName,
    private: true,
    version: '0.1.0',
    type: 'commonjs',
    scripts: {
      start: 'node server.js',
    },
  }

  const serverJs = `const http = require('http')
const fs = require('fs')
const path = require('path')

const config = JSON.parse(fs.readFileSync(path.join(__dirname, 'app-config.json'), 'utf8'))
const html = ${JSON.stringify(buildHtml(config))}

const port = Number(process.env.PORT || 3000)

const server = http.createServer((req, res) => {
  const url = req.url || '/'

  if (url === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' })
    res.end(JSON.stringify({ ok: true, appName: config.meta.appName, tables: config.database.tables.length }))
    return
  }

  if (url === '/api/config') {
    res.writeHead(200, { 'Content-Type': 'application/json' })
    res.end(JSON.stringify(config, null, 2))
    return
  }

  if (url === '/' || url === '/index.html') {
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' })
    res.end(html)
    return
  }

  res.writeHead(404, { 'Content-Type': 'application/json' })
  res.end(JSON.stringify({ error: 'Not found' }))
})

server.listen(port, () => {
  console.log('AppForge export listening on http://localhost:' + port)
})
`

  const readme = `# ${config.meta.appName}\n\nGenerated by AppForge.\n\n## Run\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\`\n`

  return {
    appName,
    files: {
      'package.json': JSON.stringify(packageJson, null, 2) + '\n',
      'server.js': serverJs,
      'app-config.json': JSON.stringify(config, null, 2) + '\n',
      'README.md': readme,
    },
  }
}

export async function writeAppScaffold(outputDir: string, config: AppConfig): Promise<ScaffoldWriteResult> {
  const scaffold = buildAppScaffold(config)
  await mkdir(outputDir, { recursive: true })

  const filePaths = Object.entries(scaffold.files).map(async ([relativePath, contents]) => {
    const absolutePath = path.join(outputDir, relativePath)
    await writeFile(absolutePath, contents, 'utf8')
    return relativePath
  })

  const files = await Promise.all(filePaths)

  return {
    outputDir,
    files,
  }
}