// lib/github-export.ts
// GitHub repo creation + file push + Vercel deploy URL generation

const GITHUB_API = 'https://api.github.com'

type AppConfig = {
  metadata?: { name?: string; description?: string }
  database?: { tables?: Array<{ name: string }> }
  api?: { endpoints?: Array<{ method: string; route: string; description?: string }> }
  ui?: { pages?: Array<{ name: string; route: string }> }
  auth?: { token_expiry?: string }
  runtime?: {
    sql?: string
    express?: string
    react?: Record<string, string>
  }
  planningDocs?: Record<string, string>
  docs?: Record<string, string>
  implementationPlan?: { prismaSchema?: string }
  artifacts?: Record<string, string>
}

// ── Internal helpers ──────────────────────────────────────────────

async function ghFetch(path: string, token: string, options: RequestInit = {}) {
  const res = await fetch(`${GITHUB_API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      ...(options.headers as Record<string, string> || {}),
    },
  })

  if (!res.ok) {
    const body = await res.json().catch(() => null)
    const msg = (body as any)?.message || res.statusText
    throw new Error(`GitHub API error (${res.status}): ${msg}`)
  }

  if (res.status === 204) return null
  return res.json()
}

async function getGitHubUsername(token: string): Promise<string> {
  const user = await ghFetch('/user', token)
  return user.login as string
}

// ── Public API ────────────────────────────────────────────────────

export type DeployProgress =
  | { step: 'creating_repo' }
  | { step: 'pushing_files'; current: number; total: number }
  | { step: 'ready'; repoUrl: string; deployUrl: string }

export async function createGithubRepo(
  token: string,
  name: string,
  description?: string
): Promise<{ owner: string; repo: string; url: string }> {
  const owner = await getGitHubUsername(token)
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50)

  const repo = await ghFetch('/user/repos', token, {
    method: 'POST',
    body: JSON.stringify({
      name: slug,
      description: description || `Generated by AppForge`,
      auto_init: false,
      private: false,
    }),
  })

  return {
    owner,
    repo: slug,
    url: (repo as any).html_url as string,
  }
}

export async function pushFilesToRepo(
  token: string,
  owner: string,
  repo: string,
  files: Record<string, string>,
  onProgress?: (progress: DeployProgress) => void
): Promise<void> {
  const entries = Object.entries(files)
  if (entries.length === 0) return

  // 1. Create blobs
  const blobShas: string[] = []
  for (let i = 0; i < entries.length; i++) {
    onProgress?.({ step: 'pushing_files', current: i + 1, total: entries.length + 2 })
    const [, content] = entries[i]
    const blob = (await ghFetch(`/repos/${owner}/${repo}/git/blobs`, token, {
      method: 'POST',
      body: JSON.stringify({ content, encoding: 'utf-8' }),
    })) as { sha: string }
    blobShas.push(blob.sha)
  }

  // 2. Create tree
  onProgress?.({ step: 'pushing_files', current: entries.length + 1, total: entries.length + 2 })
  const treeItems = entries.map(([filePath], i) => ({
    path: filePath,
    mode: '100644',
    type: 'blob' as const,
    sha: blobShas[i],
  }))

  const tree = (await ghFetch(`/repos/${owner}/${repo}/git/trees`, token, {
    method: 'POST',
    body: JSON.stringify({ tree: treeItems }),
  })) as { sha: string }

  // 3. Create commit
  onProgress?.({ step: 'pushing_files', current: entries.length + 2, total: entries.length + 2 })
  const commit = (await ghFetch(`/repos/${owner}/${repo}/git/commits`, token, {
    method: 'POST',
    body: JSON.stringify({
      message: 'Initial commit — generated by AppForge',
      tree: tree.sha,
    }),
  })) as { sha: string }

  // 4. Update HEAD ref
  await ghFetch(`/repos/${owner}/${repo}/git/refs/heads/main`, token, {
    method: 'PATCH',
    body: JSON.stringify({ sha: commit.sha, force: true }),
  })
}

export function buildVercelDeployUrl(repoUrl: string): string {
  return `https://vercel.com/new/clone?repository-url=${encodeURIComponent(repoUrl)}`
}

// ── File assembly (reuses ZIP export content, no regeneration) ────

export function assembleDeployFiles(
  config: AppConfig,
  artifacts: Record<string, string> | null
): Record<string, string> {
  const files: Record<string, string> = {}

  // Database: Prisma / SQL
  const sqlContent =
    artifacts?.['prisma.schema']
    || (config as any)?.implementationPlan?.prismaSchema
    || config?.runtime?.sql
    || ''
  if (sqlContent) {
    files['database/schema.sql'] = sqlContent
    if (sqlContent.includes('model ') || sqlContent.includes('generator ')) {
      files['database/schema.prisma'] = sqlContent
    }
  }

  // Backend: Express server
  const expressContent =
    artifacts?.['app/api/route.ts']
    || config?.runtime?.express
    || ''
  if (expressContent) {
    files['backend/server.js'] = expressContent
  }
  if (artifacts) {
    for (const [key, content] of Object.entries(artifacts)) {
      if (key.startsWith('app/api/') && key.endsWith('/route.ts') && typeof content === 'string') {
        files[`backend/${key}`] = content
      }
    }
  }

  // Frontend: React files
  if (config?.runtime?.react && typeof config.runtime.react === 'object') {
    for (const [filename, content] of Object.entries(config.runtime.react)) {
      if (typeof content === 'string') {
        files[`frontend/${filename}`] = content
      }
    }
  }
  if (artifacts) {
    for (const [key, content] of Object.entries(artifacts)) {
      if (key.startsWith('app/') && key.endsWith('/page.tsx') && typeof content === 'string') {
        files[`frontend/${key}`] = content
      }
    }
  }

  // Docs: planning documents
  const DOC_MAP: Record<string, string> = {
    'PRD.md': 'PRD - Product Requirements.md',
    'TRD.md': 'TRD - Technical Requirements.md',
    'AppFlow.md': 'App Flow.md',
    'UI-UX-BRIEF.md': 'UI-UX Brief.md',
    'BACKEND-SCHEMA.md': 'Backend Schema.md',
    'IMPLEMENTATION-PLAN.md': 'Implementation Plan.md',
  }

  const docSources = [
    artifacts,
    (config as any)?.planningDocs,
    (config as any)?.docs,
  ].find(Boolean) as Record<string, string> | undefined

  if (docSources) {
    for (const [key, content] of Object.entries(docSources)) {
      if (typeof content === 'string' && content.length > 0) {
        const fileName = DOC_MAP[key] || DOC_MAP[key.toLowerCase()] || `${key}.md`
        files[`docs/${fileName}`] = content
      }
    }
  }

  // README
  const appName = config?.metadata?.name || 'AppForge Export'
  files['README.md'] = `# ${appName}
Generated by AppForge — Natural Language Application Compiler

## Folder Structure

\`\`\`
config/
  appforge-config.json   ← Full validated app configuration
database/
  schema.sql             ← SQLite/PostgreSQL CREATE TABLE statements
  schema.prisma          ← Prisma schema (if available)
backend/
  server.js              ← Express server with JWT auth + all endpoints
  app/api/...            ← Individual API route handlers
frontend/
  App.jsx                ← React app with routing
  pages/                 ← One component per page
docs/
  PRD - Product Requirements.md
  TRD - Technical Requirements.md
  App Flow.md
  UI-UX Brief.md
  Backend Schema.md
  Implementation Plan.md
\`\`\`

## How to use
1. Import \`database/schema.sql\` into SQLite or PostgreSQL
2. Run \`node backend/server.js\` (requires: express, jsonwebtoken)
3. Open \`frontend/App.jsx\` in your React project
`

  return files
}
